### ISSUE TITLE
csw-services.sh: No useful information if service executables cannot be found

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/csw#16]
I was confused the first time I tried to execute `csw-services.sh` from a directory other than where it resides as there are no checks to see whether the services actually start:
```
$ bin/csw-services.sh start -i eth0
[INFO] Using clusterSeeds=10.0.2.15:5552
[SEED] Starting cluster seed on port: [5552] ...
[CONFIG] Starting config service on port: [5000] ...
[EVENT] Starting Event Service on port: [6379] ...
=================================================================
All the logs are stored at location: [/tmp/csw-prod/logs]
=================================================================
For assemblies or HCD's to join this cluster and use config and event service from other machine's/nodes, run below command to export env variable:
export clusterSeeds=10.0.2.15:5552
=================================================================
```

However, if I look at the logs it is obvious what happened, e.g.,
```
$ cat /tmp/csw-prod/logs/config.log 
nohup: failed to run command './csw-config-server': No such file or directory
```

Checking the exit status of `nohup` would catch this particular problem.

**Comment by kpritam** [comment]
Thank you @edwardchapin for reporting this. We will look into it.

One of the solution could be, before running script check for existence of files (bash scripts required for starting services) with something like this
`if [ -x "$file" ]`
