### ISSUE TITLE
Simplify assemblies development with Docker container

### ISSUE THREAD

**Issue by zonca** [tmtsoftware/csw#374]
@jasonweiss I was going through the installation guide at https://tmtsoftware.github.io/csw/commons/getting-started.html and it seems really complicated to set the environment right.

Do you happen to have or plan to build a Docker container preconfigured with CSW and PyCSW already setup to simplify building and testing Assemblies?

**Comment by jasonweiss** [comment]
No, we don't have plans to use Docker.  I actually don't think it's too complicated.  You will need coursier, but that program makes it easy to run CSW services without needing to install anything.  That, Java AdoptOpenJDK 11, Redis, and a few environment variables and you should be able to run components. You can even use coursier to [install Java](https://alvinalexander.com/scala/coursier-how-install-multiple-java-jdks-jvms/), if you wanted.   Coursier is also useful for running other CSW and ESW applications, like the esw-shell that allows REPL interaction with CSW and ESW components and services.

The other tools on the Getting Started page are used for development.  The Java/Scala template project for creating components sets up the development environment for you, with CSW already linked in.  For python, Allan has setup PyCSW to be installed using pip.
