### ISSUE TITLE
how to stop background csw services

### ISSUE THREAD

**Issue by zonca** [tmtsoftware/csw#378]
If this is not the right place to ask for support please advise.

I am running `csw-services start` to launch the services, I would like to run them in the background, how do I properly shut them down?
If I just kill the java process, the `redis` and `postgres` processes keep running and starting `csw-services` again fails.

**Comment by abrighton** [comment]
When you kill csw-services, Redis and Postgres are also stopped. To run csw-services in the background, just note the pid and kill it when you want to shut it down. You can see an example script that does that here: https://github.com/tmtsoftware/pycsw/blob/master/tests/runTests.sh.

**Comment by kgillies** [comment]
The slack channel #tmt-sw-programming is the place to post questions.

**Comment by zonca** [comment]
thanks @abrighton, you are right, not sure what I had done before.
Anyway now it is fine, I kill the process with `pkill -f "csw-services"` so I don't have to save the pid.
it would be better though to have `csw-services stop`.
